#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 23:05:52 2019

@author: amit
list comprehension from hackerrank
"""

x = input("enter value of x: ")
y = input("enter value of y: ")
z = input("enter value of z: ")
n = input("enter value of n: ")


print [ [ i, j, k] for i in range( x + y + 1) for j in range( y + z + 1) for k in range(z + x + 1) if ( ( i + j +k ) != n )] 

